---
# Source: social-network/charts/social-graph-mongodb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: social-graph-mongodb
spec:
  type: ClusterIP
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: social-graph-mongodb
