---
# Source: social-network/charts/media-frontend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: media-frontend
spec:
  type: ClusterIP
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8080
  selector:
    service: media-frontend
