apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --file mediaMicroservices/docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: cast-info-mongodb
  name: cast-info-mongodb
spec:
  ports:
    - name: "27024"
      port: 27024
      targetPort: 27017
  selector:
    io.kompose.service: cast-info-mongodb
status:
  loadBalancer: {}
