apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --file mediaMicroservices/docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: plot-memcached
  name: plot-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: plot-memcached
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath --file mediaMicroservices/docker-compose.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: plot-memcached
    spec:
      containers:
        - image: memcached
          name: plot-memcached
          ports:
            - containerPort: 11211
          resources: {}
      hostname: plot-memcached
      restartPolicy: Always
status: {}
