apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --file mediaMicroservices/docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: plot-memcached
  name: plot-memcached
spec:
  ports:
    - name: "11220"
      port: 11220
      targetPort: 11211
  selector:
    io.kompose.service: plot-memcached
status:
  loadBalancer: {}
