---
# Source: social-network/charts/compose-post-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: compose-post-service
spec:
  type: ClusterIP
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: compose-post-service
