---
# Source: social-network/charts/compose-post-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: compose-post-service
  name: compose-post-service
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: compose-post-service
  template:
    metadata:
      labels:
        service: compose-post-service
        app: compose-post-service
    spec: 
      shareProcessNamespace: true
      containers:
 
      - name: "compose-post-service"
        image: docker.io/yg397/social-network-microservices:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        command: 
        - ComposePostService        
        volumeMounts:
        - name: compose-post-service-config
          mountPath: /social-network-microservices/config/jaeger-config.yml
          subPath: jaeger-config.yml
        - name: compose-post-service-config
          mountPath: /social-network-microservices/config/service-config.json
          subPath: service-config.json
      volumes:
      - name: compose-post-service-config
        configMap:
          name: compose-post-service
      hostname: compose-post-service
      restartPolicy: Always
