---
# Source: social-network/charts/home-timeline-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: home-timeline-service
spec:
  type: ClusterIP
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: home-timeline-service
