apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --file mediaMicroservices/docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: review-storage-memcached
  name: review-storage-memcached
spec:
  ports:
    - name: "11215"
      port: 11215
      targetPort: 11211
  selector:
    io.kompose.service: review-storage-memcached
status:
  loadBalancer: {}
