apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --file mediaMicroservices/docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: compose-review-service
  name: compose-review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: compose-review-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath --file mediaMicroservices/docker-compose.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: compose-review-service
    spec:
      containers:
        - command:
            - ComposeReviewService
          image: yg397/media-microservices
          name: compose-review-service
          ports:
            - containerPort: 9090
          resources: {}
      hostname: compose-review-service
      restartPolicy: Always
status: {}
