apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --file mediaMicroservices/docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: movie-info-service
  name: movie-info-service
spec:
  ports:
    - name: "10012"
      port: 10012
      targetPort: 9090
  selector:
    io.kompose.service: movie-info-service
status:
  loadBalancer: {}
