apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --file mediaMicroservices/docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: text-service
  name: text-service
spec:
  ports:
    - name: "10003"
      port: 10003
      targetPort: 9090
  selector:
    io.kompose.service: text-service
status:
  loadBalancer: {}
