apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --file mediaMicroservices/docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: dns-media
  name: dns-media
spec:
  ports:
    - name: "5380"
      port: 5380
      targetPort: 5380
  selector:
    io.kompose.service: dns-media
status:
  loadBalancer: {}
