---
# Source: social-network/charts/user-memcached/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: user-memcached
  name: user-memcached
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: user-memcached
  template:
    metadata:
      labels:
        service: user-memcached
        app: user-memcached
    spec: 
      shareProcessNamespace: true
      containers:
      - name: perf
        image: suvigyajain1/perf
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_PTRACE
        tty: true
        stdin: true 
      - name: "user-memcached"
        image: docker.io/library/memcached:1.6.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11211        
        volumeMounts:
        - name: user-memcached-config
          mountPath: /social-network-microservices/config/service-config.json
          subPath: service-config.json
      volumes:
      - name: user-memcached-config
        configMap:
          name: user-memcached
      hostname: user-memcached
      restartPolicy: Always
