---
# Source: social-network/charts/post-storage-memcached/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: post-storage-memcached
spec:
  type: ClusterIP
  ports:
  - name: "11211"
    port: 11211
    targetPort: 11211
  selector:
    service: post-storage-memcached
