---
# Source: social-network/charts/jaeger/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: NodePort
  ports:
  - name: "5775"
    port: 5775
    protocol: UDP
    nodePort: 32000
    targetPort: 5775
  - name: "6831"
    port: 6831
    nodePort: 32001
    protocol: UDP
    targetPort: 6831
  - name: "6832"
    port: 6832
    nodePort: 32002
    protocol: UDP
    targetPort: 6832
  - name: "5778"
    port: 5778
    nodePort: 32003
    targetPort: 5778
  - name: "16686"
    port: 16686
    nodePort: 32004
    targetPort: 16686
  - name: "14268"
    port: 14268
    nodePort: 32005
    targetPort: 14268
  - name: "9411"
    port: 9411
    nodePort: 32006
    targetPort: 9411
  selector:
    service: jaeger
