apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --file mediaMicroservices/docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: movie-review-redis
  name: movie-review-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: movie-review-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath --file mediaMicroservices/docker-compose.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: movie-review-redis
    spec:
      containers:
        - image: redis
          name: movie-review-redis
          ports:
            - containerPort: 6379
          resources: {}
      hostname: movie-review-redis
      restartPolicy: Always
status: {}
