---
# Source: social-network/charts/social-graph-mongodb/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: social-graph-mongodb
  labels:
    socialnetwork/service: social-graph-mongodb
data:
  mongod.conf: |    
    net:
      tls:
        mode: disabled
