apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath --file mediaMicroservices/docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rating-redis
  name: rating-redis
spec:
  ports:
    - name: "6382"
      port: 6382
      targetPort: 6379
  selector:
    io.kompose.service: rating-redis
status:
  loadBalancer: {}
