---
# Source: social-network/charts/post-storage-mongodb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: post-storage-mongodb
spec:
  type: ClusterIP
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: post-storage-mongodb
