---
# Source: social-network/charts/url-shorten-mongodb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: url-shorten-mongodb
spec:
  type: ClusterIP
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: url-shorten-mongodb
