---
# Source: social-network/charts/url-shorten-memcached/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: url-shorten-memcached
  name: url-shorten-memcached
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: url-shorten-memcached
  template:
    metadata:
      labels:
        service: url-shorten-memcached
        app: url-shorten-memcached
    spec: 
      shareProcessNamespace: true
      containers:

      - name: "perf"
        image: suvigyajain1/perf
        securityContext:
          privileged: true
          capabilities:
            add: 
            - SYS_PTRACE
        tty: true
        stdin: true
 
      - name: "url-shorten-memcached"
        image: docker.io/library/memcached:1.6.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11211   
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]     
        volumeMounts:
        - name: url-shorten-memcached-config
          mountPath: /social-network-microservices/config/jaeger-config.yml
          subPath: jaeger-config.yml
        - name: url-shorten-memcached-config
          mountPath: /social-network-microservices/config/service-config.json
          subPath: service-config.json
      volumes:
      - name: url-shorten-memcached-config
        configMap:
          name: url-shorten-memcached
      hostname: url-shorten-memcached
      restartPolicy: Always
