---
# Source: social-network/charts/url-shorten-memcached/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: url-shorten-memcached
spec:
  type: ClusterIP
  ports:
  - name: "11211"
    port: 11211
    targetPort: 11211
  selector:
    service: url-shorten-memcached
