---
# Source: social-network/charts/user-mention-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-mention-service
spec:
  type: ClusterIP
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: user-mention-service
