---
# Source: social-network/charts/user-timeline-mongodb/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-timeline-mongodb
  labels:
    socialnetwork/service: user-timeline-mongodb
data:
  mongod.conf: |    
    net:
      tls:
        mode: disabled
