---
# Source: social-network/charts/user-timeline-mongodb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-timeline-mongodb
spec:
  type: ClusterIP
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: user-timeline-mongodb
