---
# Source: social-network/charts/media-mongodb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: media-mongodb
  name: media-mongodb
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: media-mongodb
  template:
    metadata:
      labels:
        service: media-mongodb
        app: media-mongodb
    spec: 
      shareProcessNamespace: true
      containers:
      - name: perf
        image: suvigyajain1/perf
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_PTRACE
        tty: true
        stdin: true 
      - name: "media-mongodb"
        image: docker.io/library/mongo:4.4.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        args:
        - --config
        - /social-network-microservices/config/mongod.conf        
        volumeMounts:
        - name: media-mongodb-config
          mountPath: /social-network-microservices/config/mongod.conf
          subPath: mongod.conf
      volumes:
      - name: media-mongodb-config
        configMap:
          name: media-mongodb
      hostname: media-mongodb
      restartPolicy: Always
