---
# Source: social-network/charts/media-mongodb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: media-mongodb
spec:
  type: ClusterIP
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: media-mongodb
