---
# Source: social-network/charts/text-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: text-service
spec:
  type: ClusterIP
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: text-service
