---
# Source: social-network/charts/url-shorten-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: url-shorten-service
spec:
  type: ClusterIP
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: url-shorten-service
