---
# Source: social-network/charts/url-shorten-mongodb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: url-shorten-mongodb
  name: url-shorten-mongodb
spec: 
  replicas: 1
  selector:
    matchLabels:
      service: url-shorten-mongodb
  template:
    metadata:
      labels:
        service: url-shorten-mongodb
        app: url-shorten-mongodb
    spec: 
      shareProcessNamespace: true
      containers:

      - name: "perf"
        image: suvigyajain1/perf
        securityContext:
          privileged: true
          capabilities:
            add: 
            - SYS_PTRACE
        tty: true
        stdin: true
 
      - name: "url-shorten-mongodb"
        image: docker.io/library/mongo:4.4.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        args:
        - --config
        - /social-network-microservices/config/mongod.conf    
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]    
        volumeMounts:
        - name: url-shorten-mongodb-config
          mountPath: /social-network-microservices/config/mongod.conf
          subPath: mongod.conf
      volumes:
      - name: url-shorten-mongodb-config
        configMap:
          name: url-shorten-mongodb
      hostname: url-shorten-mongodb
      restartPolicy: Always
