---
# Source: social-network/charts/social-graph-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: social-graph-service
spec:
  type: ClusterIP
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: social-graph-service
